<a href="https://colab.research.google.com/github/SANAD343/Logistic_Regression_Binary_Classification/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [4]:
print(dataset.DESCR) #gives the description of the dataset

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
print(dataset.keys()) #print the keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
import pandas as pd
import numpy as np

In [8]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
print(dataset.target) # 0 represents the setosa,  1 represents the Versicolour, 2 represents the Virginica

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
df["target"]=dataset.target #adding target values within the dataframe

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
df["target"].unique()

array([0, 1, 2])

In [14]:
#considering the binary classification problem

In [16]:
df[df["target"]!=2] #getting only 0 and 1 as targets

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [17]:
df_copy=df[df["target"]!=2] #creating a new copy of dataset while skipping target values as 2

In [18]:
df_copy["target"].unique() #checking if the above command executed or not

array([0, 1])

In [19]:
#we need to perform train test split

In [33]:
x=df_copy.iloc[:,:-1] #independent Feature
y=df_copy.iloc[:,-1] #dependent Feature

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.20, random_state=42)

In [22]:
#now apply logistic regression model

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
classification=LogisticRegression(max_iter=500)

In [37]:
classification

LogisticRegression(max_iter=500)

In [38]:
classification.fit(x_train,y_train)

LogisticRegression(max_iter=500)

In [39]:
#now we can do the prediction

In [40]:
y_pred=classification.predict(x_test)

In [41]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [42]:
#calculate the confision metrics, accuracy, classification report

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [44]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [45]:
print(accuracy_score(y_test,y_pred))

1.0


In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [ ]:
# cross validation - splitting the training data into training data and validation data

In [47]:
from sklearn.model_selection import KFold

In [48]:
cv=KFold(n_splits=5)

In [49]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [50]:
from sklearn.model_selection import cross_val_score

In [52]:
##score for all the cross validation
score=cross_val_score(classification,x_train,y_train,scoring="accuracy",cv=cv)

In [53]:
score

array([1., 1., 1., 1., 1.])

In [54]:
#mean of cv score

np.mean(score)

1.0

In [55]:
## Lets see more complex data

# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [58]:
complex_class_model=LogisticRegression(max_iter=200)

In [59]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [60]:
y_pred_complex=complex_class_model.predict(X_test)

In [61]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [62]:
## Cross Validatiuon
cv=KFold(n_splits=5)
cross_val_score(complex_class_model,X_train,y_train,cv=cv)

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])